[package]
name = "braiinspool"
version = "0.1.1"
edition = "2021"
description = "Braiins Pool API"
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>"]
homepage = "https://github.com/shadowylab/braiinspool"
repository = "https://github.com/shadowylab/braiinspool.git"
license = "MIT"
readme = "README.md"
keywords = ["bitcoin", "braiins", "slushpool", "mining"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "socks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"

[dev-dependencies]
tokio = { version =  "1", features = ["full"] }
