[package]
name = "braiinspool"
version = "0.1.0"
edition = "2021"
description = "Braiins Pool API SDK"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/braiins-rust-sdk"
repository = "https://github.com/yukibtc/braiins-rust-sdk.git"
license = "MIT"
readme = "README.md"
keywords = ["bitcoin", "braiins", "braiinspool", "slushpool", "mining", "sdk"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "socks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"

[dev-dependencies]
tokio = { version =  "1", features = ["full"] }